name: Issues

on: push

jobs: 
  Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Display Info
        run : echo '${{ toJSON( github ) }}'